variable "namespace_name" {}
variable "deployment_name" {}
variable "container_name" {}
variable "container_image" {}
variable "container_port" {}
variable "replicas" {}
variable "service_name" {}
variable "service_port" {}
variable "cluster_endpoint" {}
variable "cluster_ca_certificate" {}
