name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Authenticate to Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}
      run: |
        echo "${GOOGLE_APPLICATION_CREDENTIALS}" > ${HOME}/gcloud_key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud_key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

  build-and-deploy:
    name: Build and Deploy API
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry (GCR)
      run: |
        echo "${{ secrets.GCP_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/api:latest

    - name: Deploy API to GKE
      run: terraform apply -auto-approve

  verify:
    name: Verify API
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Verify API Endpoint
      run: |
        API_URL=$(terraform output -raw api_url)
        RESPONSE=$(curl -s $API_URL/time)
        if echo "$RESPONSE" | grep -q '"current_time"'; then
          echo "API is accessible and returned the correct response."
        else
          echo "API test failed."
          exit 1
        fi
