name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    environment: Development
    name: Build, Push Docker Image, and Deploy API
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Authenticate to Google Cloud
      run: |
        echo ${{ secrets.GCP_KEY }} | base64 --decode > ${HOME}/gcloud_key.json
        export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud_key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcloud_key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Terraform Init Dockerfile
      run: terraform init

    - name: Terraform Apply Dockerfile
      run: terraform apply -auto-approve -var "docker_registry_name=${{ secrets.DOCKER_USERNAME }}" -var "docker_image_name=api" -var "docker_username=${{ secrets.DOCKER_USERNAME }}" -var "docker_password=${{ secrets.DOCKER_PASSWORD }}"

    - name: Terraform Init Infrastrusture
      run: terraform init
      working-directory: terraform/
    - name: Terraform Plan Infrastrusture
      run: terraform plan -out=tfplan.binary -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "container_image=${{ secrets.DOCKER_USERNAME }}/api:latest" -var-file="roles.tfvars"
      working-directory: terraform/

    - name: Convert Terraform Plan to JSON
      run: terraform show -json tfplan.binary > tfplan.json
      working-directory: terraform/

    - name: Run OPA to validate Terraform plan
      run: |
        opa eval --input tfplan.json --data policy.rego "data.tfplan.deny"
      working-directory: terraform/

    - name: Terraform Apply Infrastrusture
      if: success()
      run: terraform apply -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "container_image=${{ secrets.DOCKER_USERNAME }}/api:latest" -var-file="roles.tfvars"
      working-directory: terraform/
  verify:
    environment: Development
    name: Verify API
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Verify API Endpoint
      run: |
        API_URL=$(terraform output -raw api_url)
        RESPONSE=$(curl -s $API_URL/time)
        if echo "$RESPONSE" | grep -q '"current_time"'; then
          echo "API is accessible and returned the correct response."
        else
          echo "API test failed."
          exit 1
        fi
      working-directory: terraform/
